apiVersion: v1
kind: PersistentVolume
metadata:
  name: upload-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: upload-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - siamatic-worker1
  hostPath:
    path: /mnt/data/upload
    type: DirectoryOrCreate